name: Build Maven xRegistry

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'maven/**'
      - '.github/workflows/build-maven.yml'
  pull_request:
    paths:
      - 'maven/**'
      - '.github/workflows/build-maven.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ${{ github.repository }}/xregistry-maven-bridge

jobs:
# ───────────────────────────────────────────────────────── build ─────
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    outputs:
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v4

      - uses: sigstore/cosign-installer@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.sha }}
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref,'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref,'refs/tags/v') }}
            type=ref,event=branch
            type=ref,event=pr
      - id: build
        uses: docker/build-push-action@v5
        with:
          context: ./maven
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max
          provenance: mode=max

      - name: Sign image (OIDC)
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_YES: "true"
        run: |
          REF="${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}@${{ steps.build.outputs.digest }}"
          cosign sign "${REF}"
# ──────────────────────────────────────────────────────── verify ─────
  verify:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: read
      id-token: write

    steps:
      - uses: sigstore/cosign-installer@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify signature
        run: |
          REF="${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}@${{ needs.build.outputs.digest }}"
          cosign verify \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com \
            --certificate-identity "https://github.com/${{ github.workflow_ref }}" \
            "${REF}" 